=== glmquint/SecurePOS/src/DataObjects/Schema/PreparationSystemConfigSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "db": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "table_name": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "table_name"
      ]
    },
    "phase_tracker": {
      "type": "object",
      "properties": {
        "evaluation_phase_duration": {
          "type": "integer"
        },
        "phase": {
          "type": "string"
        },
        "production_phase_duration": {
          "type": "integer"
        }
      },
      "required": [
        "evaluation_phase_duration",
        "phase",
        "production_phase_duration"
      ]
    },
    "preparation_sys_receiver": {
      "type": "object",
      "properties": {
        "endpoints": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "callback": {
                  "type": "string"
                },
                "endpoint": {
                  "type": "string"
                },
                "schema": {
                  "type": "string"
                }
              },
              "required": [
                "callback",
                "endpoint",
                "schema"
              ]
            },
            {
              "type": "object",
              "properties": {
                "callback": {
                  "type": "string"
                },
                "endpoint": {
                  "type": "string"
                },
                "schema": {
                  "type": "string"
                }
              },
              "required": [
                "callback",
                "endpoint",
                "schema"
              ]
            }
          ]
        }
      },
      "required": [
        "endpoints"
      ]
    },
    "prepared_session_creator": {
      "type": "object",
      "properties": {
        "production_system_receiver": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string"
            }
          },
          "required": [
            "url"
          ]
        },
        "segregation_system_receiver": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string"
            }
          },
          "required": [
            "url"
          ]
        }
      },
      "required": [
        "production_system_receiver",
        "segregation_system_receiver"
      ]
    },
    "raw_session_creator": {
      "type": "object",
      "properties": {
        "label_receiver": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string"
            }
          },
          "required": [
            "url"
          ]
        },
        "number_of_systems": {
          "type": "integer"
        },
        "raw_session_receiver": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string"
            }
          },
          "required": [
            "url"
          ]
        }
      },
      "required": [
        "label_receiver",
        "number_of_systems",
        "raw_session_receiver"
      ]
    },
    "raw_session_topic": {
      "type": "string"
    }
  },
  "required": [
    "db",
    "phase_tracker",
    "preparation_sys_receiver",
    "prepared_session_creator",
    "raw_session_creator",
    "raw_session_topic"
  ]
}

=== glmquint/SecurePOS/src/Ingestion/config/PreparationSystemConfig.json
{
  "raw_session_topic" : "RawSessionTopic",
  "phase_tracker" : {
      "phase" : "Development",
      "production_phase_duration" : 2,
      "evaluation_phase_duration" : 1
  },
  "db" : {
    "name" : "record",
    "table_name" : "record"
  },
  "preparation_sys_receiver" : {
    "endpoints" : [
      {
        "endpoint" : "/record",
        "callback" : "receiveRecord",
        "schema"   : "RecordSchema.json"
      },
      {
        "endpoint" : "/raw_session",
        "callback" : "receiveRawSession",
        "schema"   : "RawSessionSchema.json"
      }
    ]
  },
  "raw_session_creator" : {
    "number_of_systems" : 4,
    "raw_session_receiver" : {
      "url" : "http://localhost:5005/raw_session"
    },
    "label_receiver" : {
      "url" : "http://localhost:5004/evaluation_security_label"
    }
  },
  "prepared_session_creator" : {
    "segregation_system_receiver" : {
      "url" : "http://localhost:5001/segregationSystem"
    },
    "production_system_receiver" : {
      "url" : "http://localhost:5003/PreparedSession"
    }
  }
}
